name: Hello_world_execution
on: workflow_dispatch

jobs:
  build:
    name: Build the code
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: echo "Build the JAVA application"

  test:
    name: Test the app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Application test
        run: echo "Test the JAVA application"

  deploy:
    name: Deploy to K8s
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy step
        run: echo "Deploy to K8s"


       
      
        
    

