name: Hello_world execution
on: workflow_dispatch
jobs:
  hellos:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Multiple cmds
        run: |
          echo "Start Build"
          pwd
          ls -la
          echo "Completed Successfully"

    

