name: Hello_world_execution
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the code
        run: echo "Build the JAVA application"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Application test
        run: echo "Test the JAVA application"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy step
        run: echo "Deploy to K8s"


       
      
        
    

